## Практика 1. Базові операції

Більш детально можна почитати  [тут](https://towardsdatascience.com/top-10-matrix-operations-in-numpy-with-examples-d761448cb7a8). 

Пригадаємо базові операції з векторами і матрицями. 

In [13]:
import numpy as np

a = np.array([1, 2, 3])                          # введемо вектори як 1D numpy arrays
b = np.array([4, 5, 6])
print("\n скалярний добуток:", np.inner(a, b))   # скалярний добуток, \n перед словом означає новий рядок
print("dot:", np.dot(a, b))


 скалярний добуток: 32
dot: 32


Ми можемо задавати матриці як масиви, або як матриці: 

In [4]:
# Матриці як масиви
a = np.array([[1, 2], [3, 4]])  
b = np.array([[5, 6, 7], [8, 9, 10]])
print(type(a))

<class 'numpy.ndarray'>


In [5]:
# Мариці як матриці
c = np.matrix([[1, 2], [3, 4]])
d = np.matrix([[5, 6, 7], [8, 9, 10]])
print(type(c))

<class 'numpy.matrix'>


Допуток прир цьому обчислюється однаково: 

In [6]:
print("\nдобуток масивів")
print(np.dot(a, b))
print("\nдобуток матриць")
print(np.dot(c, d))


добуток масивів
[[21 24 27]
 [47 54 61]]

добуток матриць
[[21 24 27]
 [47 54 61]]


Можна також використовувати $@$ (і для масивів, і для матриць):

In [7]:
print(c@d)

[[21 24 27]
 [47 54 61]]


In [8]:
print(a@b)

[[21 24 27]
 [47 54 61]]


Транспонування:

In [9]:
a = np.array([[1, 2], [3, 4], [5, 6]])
print(a)

print("\nЗа допомоги np.transpose(a)")
print(np.transpose(a))

print("\nЗа допомоги ndarray.transpose()")
print(a.transpose())

print("\nЗа допомоги ndarray.T")
print(a.T)

[[1 2]
 [3 4]
 [5 6]]

За допомоги np.transpose(a)
[[1 3 5]
 [2 4 6]]

За допомоги ndarray.transpose()
[[1 3 5]
 [2 4 6]]

За допомоги ndarray.T
[[1 3 5]
 [2 4 6]]


Слід матриці:

In [4]:
a = np.array([[2, 2, 1],
               [1, 3, 1],
               [1, 2, 2]])
print("a = ")
print(a)
print("\nСлід:", a.trace())  
print("Слід:", sum(a.diagonal()))  

a = 
[[2 2 1]
 [1 3 1]
 [1 2 2]]

Слід: 7
Слід: 7


Детермінант матриці:

In [5]:
a = np.array([[2, 2, 1],
               [1, 3, 1],
               [1, 2, 2]])
det = np.linalg.det(a)
print("\nдетермінант:", det)            # значення, я є
print("\nокруглений детермінант:", np.round(det))  # округлити 



детермінант: 4.999999999999999

округлений детермінант: 5.0


Для того, щоб округлити, застосуємо функцію  round(number, digits). Наприклад, 

In [11]:
round(5.456789,2)

5.46

Обернена матриця:

In [6]:
inv = np.linalg.inv(a)
print("\nобернена матриця a = ")
print(inv)


обернена матриця a = 
[[ 0.8 -0.4 -0.2]
 [-0.2  0.6 -0.2]
 [-0.2 -0.4  0.8]]


 Псевдо-обернена матриця, якщо детермінант =0. 

In [10]:
a = np.array([[2, 8],
               [1, 4]])
det = np.linalg.det(a)
print("\nдетермінант:", np.round(det))
pinv = np.linalg.pinv(a)
print("\nпсевдо-обернена матриця a = ")
print(pinv)


детермінант: 0.0

псевдо-обернена матриця a = 
[[0.02352941 0.01176471]
 [0.09411765 0.04705882]]


Власні вектори і власні числа:

In [8]:
a = np.array([[2, 2, 1],
               [1, 3, 1],
               [1, 2, 2]])
w, v = np.linalg.eig(a)
print("\nвласні числа:")
print(w)
print("\nвласні вектори:")
print(v)


власні числа:
[5. 1. 1.]

власні вектори:
[[ 0.57735027  0.90453403  0.36601928]
 [ 0.57735027 -0.30151134 -0.55609927]
 [ 0.57735027 -0.30151134  0.74617926]]
