## Практика 5.  Лінійна пегресія

In [1]:
import numpy as np
import math
from sklearn.linear_model import LinearRegression
import statsmodels.api as sm
from statsmodels.api import OLS  # ordinary least squares estimates
import pandas as pd
from sklearn import linear_model
from statsmodels.multivariate.manova import MANOVA

### Приклад 1. Одновимірна модель, лінійна регресія. 

Дані з 'Квартету Аскомбе', не з Ренчер. 

In [2]:
y = np.array([8.04,6.95,7.58,8.81,8.33,9.96,7.24,4.26,10.84,4.82,5.68])
x1 = [10,8,13,9,11,14,6,4,12,7,5]
x = np.array([10,8,13,9,11,14,6,4,12,7,5]).reshape((-1,1))
w = [math.sqrt(y[i]) for i in range(len(x))]+ np.random.normal(0,1,len(y))

In [3]:
model = LinearRegression().fit(x, y)
r_sq = model.score(x, y)
print('coefficient of determination:', r_sq)   # R^2

coefficient of determination: 0.666542459508775


In [4]:
print('intercept:', model.intercept_)
print('slope:', model.coef_)


intercept: 3.0000909090909103
slope: [0.50009091]


Ддобавимо ще одну змінну (щоб зробити множинну регресію):

In [5]:
Z = [[x1[i],w[i]] for i in range(len(x))]
Z

[[10, 1.6221226213215554],
 [8, 3.4960709155889367],
 [13, 1.9880683324598758],
 [9, 4.057426505700013],
 [11, 1.755013956383109],
 [14, 3.2433671764815295],
 [6, 4.533965122697768],
 [4, 1.5582582937001634],
 [12, 3.1842377972785494],
 [7, 3.2074610391652127],
 [5, 1.8933643704035703]]

In [6]:
model2 = LinearRegression().fit(Z, y)
print('intercept:', model2.intercept_)
print('slope:', model2.coef_)

intercept: 1.4421487308445995
slope: [0.50021155 0.56076562]


Зробимо повний аналіз моделі.

In [7]:
Z2 =  [[1,x1[i],w[i]] for i in range(len(x))]
Z2 = np.asarray(Z2)
model2 = LinearRegression().fit(Z2, y)
model3 = sm.OLS(y,Z2)
results = model3.fit() 
print(results.summary())

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.751
Model:                            OLS   Adj. R-squared:                  0.689
Method:                 Least Squares   F-statistic:                     12.06
Date:                Mon, 13 Mar 2023   Prob (F-statistic):            0.00385
Time:                        21:53:37   Log-Likelihood:                -15.235
No. Observations:                  11   AIC:                             36.47
Df Residuals:                       8   BIC:                             37.66
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          1.4421      1.399      1.031      0.3

C:\Users\vica\anaconda3\lib\site-packages\scipy\stats\stats.py:1541: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=11
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "


Окремі обчислення: 

In [8]:
print(results.params) # коефіцієнти

[1.44214873 0.50021155 0.56076562]


In [9]:
print(results.rsquared) #R2

0.7509527004309737


In [10]:
print(results.bse) # std err

[1.39931559 0.10807645 0.3405491 ]


In [11]:
print(results.f_pvalue)  # Prob  F-statistic   

0.0038470457234724277


In [12]:
dir(results) # інші параметри- треба дивитися атрібути
# https://www.statsmodels.org/devel/generated/statsmodels.regression.linear_model.OLSResults.html

['HC0_se',
 'HC1_se',
 'HC2_se',
 'HC3_se',
 '_HCCM',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_abat_diagonal',
 '_cache',
 '_data_attr',
 '_data_in_cache',
 '_get_robustcov_results',
 '_is_nested',
 '_use_t',
 '_wexog_singular_values',
 'aic',
 'bic',
 'bse',
 'centered_tss',
 'compare_f_test',
 'compare_lm_test',
 'compare_lr_test',
 'condition_number',
 'conf_int',
 'conf_int_el',
 'cov_HC0',
 'cov_HC1',
 'cov_HC2',
 'cov_HC3',
 'cov_kwds',
 'cov_params',
 'cov_type',
 'df_model',
 'df_resid',
 'diagn',
 'eigenvals',
 'el_test',
 'ess',
 'f_pvalue',
 'f_test',
 'fittedvalues',
 'fvalue',
 'get_influence',
 'get_prediction',
 'get_robustcov_results',
 'info_c

In [13]:
# https://www.accelebrate.com/blog/interpreting-results-from-linear-regression-is-the-data-appropriate 
# більше пор останній блок резульатів 

In [14]:
# дещо можна було отримати і з model2
print('Intercept: \n', model2.intercept_)  # коефіцієнт при вільному доданку, тобто при 1
print('Coefficients: \n', model2.coef_)    # оцінки коефіцієнтів


Intercept: 
 1.4421487308445995
Coefficients: 
 [0.         0.50021155 0.56076562]


Оцінка матриці $B$ вручну:

In [15]:
B =  np.linalg.inv(Z2.T @ Z2) @ (Z2.T @ y)
B

array([1.44214873, 0.50021155, 0.56076562])

### Приклад 2.  Багатовимірна регресія: Приклад  10.4.2 Rencher

In [16]:
df1 = np.loadtxt('T10_1_CHEM.DAT', dtype=float)
data2 = pd.DataFrame(df1[:,1:], columns=['Y1','Y2','Y3','X1', 'X2', 'X3'])
print(data2.head())

     Y1    Y2    Y3     X1    X2   X3
0  41.5  45.9  11.2  162.0  23.0  3.0
1  33.8  53.3  11.2  162.0  23.0  8.0
2  27.7  57.5  12.7  162.0  30.0  5.0
3  21.7  58.8  16.0  162.0  30.0  8.0
4  19.9  60.6  16.2  172.0  25.0  5.0


In [17]:
X = df1[:, 4:]  
Y = df1[:,1:4]

In [18]:
model_ols =  linear_model.LinearRegression(normalize=False)
results2 = model_ols.fit(X,Y)
print(model_ols.coef_)   # Отримаємо матрицю В  
print(model_ols.intercept_)

[[-1.54596082 -1.42455873 -2.23736565]
 [ 0.40455059  0.29298999  1.03380047]
 [ 0.91392477  0.89947254  1.15348549]]
[ 332.11098334  -26.03526431 -164.0789411 ]


In [19]:
fit1 = MANOVA.from_formula('Y ~ X', data= data2)
print(fit1.mv_test())

                  Multivariate linear model
                                                              
--------------------------------------------------------------
       Intercept         Value  Num DF  Den DF F Value  Pr > F
--------------------------------------------------------------
          Wilks' lambda  0.0220 3.0000 13.0000 192.3656 0.0000
         Pillai's trace  0.9780 3.0000 13.0000 192.3656 0.0000
 Hotelling-Lawley trace 44.3921 3.0000 13.0000 192.3656 0.0000
    Roy's greatest root 44.3921 3.0000 13.0000 192.3656 0.0000
--------------------------------------------------------------
                                                              
--------------------------------------------------------------
           X             Value  Num DF  Den DF F Value  Pr > F
--------------------------------------------------------------
          Wilks' lambda  0.0332 9.0000 31.7892  10.7870 0.0000
         Pillai's trace  1.0579 9.0000 45.0000   2.7235 0.0126
 Hotelling-